---
title: "First Post: Introduction"
description: |
 Welcome to my blog Text as data, please click to check initial draft. 
  Kindly look for future posts for furthur information. New posts every week :-)... 
author:
  - name: Sathvik Thogaru 
    url: https://thogarusathvik.github.io/Text-as-Data-Project/
    
date: 02-18-2022
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
body {
text-align: justify}
</style>


Twitter, Facebook, Reddit and other social media platforms represent a large and largely untapped resource for social data and evidence.The data in these platforms is vast, contains variety of topics that people discuss on the daily basis regardless of geographical location. This data that is generated on the daily basis provides a key/main source of information for anyone who wants to study science, communication, people opinions and situations happening across the world at the same time. 

These platforms provide data through number of applicatyion Programming Interfaces(API). Although it may be diificult or sometimes not possible to obtain data from these platforms, they help in qualitative and quantitative research.

Covid-19 outbreak was nothing less than the biggest nightmare the humanity has gone through that has changed the lives of millions upsidedown in no time and almost everyone have suffered. Even with the research advancements we see and develop every single day, yet we still haven't figured out completely to eliminate the virus. So we adapted ourselves to live with it but that didn't happen overnight. In my study I am trying to collect the voices of people across all borders what they shared on social media platforms like Twitter, Reddit etc., and differentiate the data according to the phases of the outbreak while listing the most common problems that masses faced at each stage and establish the relation on how the trend shifting happened overtime and who were most impacted by it. 

#EMPLOYMENT & RESIGNATION TREND
#ROLE OF CHINA IN THE SPREAD OF COVID
#VACCINE DEVELOPMENT & WHO RESPONSE
#TRAVEL BAN & COVID RESTRICTIONS 
#TOP 10 COUNTRIES WITH COVID CASES & THE TOP TWEETS SENTIMENTS ( REGION WISE AFFECTED)














