---
title: "Second Post: Data Collection"
description: |
  Data collection and Characteristics of Data Source
author:
  - name: Sathvik Thogaru
    url: https://thogarusathvik.github.io/Text-as-Data-Project/
date: 02-21-2022
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style>
body {
text-align: justify}
</style>


For my Research Question  which I have stated in my First post, I will collect the `Tweets` of all the possible `Covid19` Data that I can get. The Data will be collected using the `Twitter API`. The Twitter API helps to `read` and `write` Twitter data. It is also helpful to `compose tweets`, `read profiles`, and `access followers' data` and a high volume of tweets on particular subjects in specific locations. API stands for `Application Programming Interface`. 

To get access to Twitter API, I will first sign up for `Twitter Developer Account`,then get access to my `API keys` and `Tokens`. After getting the required Keys and Tokens I make my initial request by using the `search_tweets()` fuction in package `rtweet` and store the data in a file which I will be using for my research.

The initial glimpse of the data and its content will be availabe in the next post. 










